# Generated by Django 3.2 on 2021-05-24 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='category',
            field=models.CharField(blank=True, choices=[('Flooring ', 'FLOORING'), ('Plumbing', 'PLUMBING'), ('Fitting', 'FITTING'), ('Other', 'OTHER')], max_length=20, null=True, verbose_name='Select your work type :'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='HiringLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='State')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.labour')),
            ],
        ),
    ]
