# Generated by Django 3.2 on 2021-05-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210525_0226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HiringLabour',
        ),
    ]
