# Generated by Django 3.2 on 2021-05-26 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_labour_is_hired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.engineer')),
                ('labr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.labour')),
            ],
        ),
    ]
